version: '2'

networks:
  healthcare-network-1:
    name: healthcare-network-1

services:

  ca_hospital:
    image: hyperledger/fabric-ca:1.5.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.hospital
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../consortium/fabric-ca/hospital:/etc/hyperledger/fabric-ca-server
    container_name: ca.hospital
    hostname: ca.hospital
    networks:
      - healthcare-network-1

