version: '2'

networks:
  healthcare-network-1:
    name: healthcare-network-1

services:

  ca_insurance:
    image: hyperledger/fabric-ca:1.5.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.insurance
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../consortium/fabric-ca/insurance:/etc/hyperledger/fabric-ca-server
    container_name: ca.insurance
    hostname: ca.insurance
    networks:
      - healthcare-network-1
