version: '2'

networks:
  healthcare-network-1:
      name: healthcare-network-1
      external: true

services:

  ca_hospital:
    image: hyperledger/fabric-ca:2.2
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.hospital
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../consortium/fabric-ca/hospital:/etc/hyperledger/fabric-ca-server
    container_name: ca.hospital
    hostname: ca.hospital
    networks:
      - healthcare-network-1

  ca_insurance:
    image: hyperledger/fabric-ca:2.2
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.insurance
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../consortium/fabric-ca/insurance:/etc/hyperledger/fabric-ca-server
    container_name: ca.insurance
    hostname: ca.insurance
    networks:
      - healthcare-network-1

  ca_orderer:
    image: hyperledger/fabric-ca:2.2
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../consortium/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - healthcare-network-1
