NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/34.101.204.172-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/34.101.204.172-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/34.101.204.172-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/34.101.204.172-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer
